### ISSUE TITLE
Compare our solution with what findy is doing

### ISSUE THREAD

**Issue by ArPhil** [IDunion/OpenIDIDComm#8]
It seems, that findy is also experimenting with integration of Indy into the OpenID (connect) space:

https://github.com/findy-network/findy-oidc-provider
https://findynet.fi/en/news/oidf/

We should check, if there are synergies.

**Comment by janawueTUB** [comment]
It seems like they‘re using an intrgration of DIDComm similar to ours (meaning they establish the DIDComm channel really early). As far as I understood they’re is no possibility to create a connection without creating a DIDComm channel. 

On their website they say that they’re willing to collaborate with others so maybe we should contact them in order to exchange knowledge and ideas.

**Comment by void1042** [comment]
Looks like they use an didcomm-invitation based approach, which, I believe, we also considered at some point. Basically, instead of rendering a login form for the user to type name and passwort into, they render an invitation as a qr-code and then the user logs by sending a credential over didcomm.

**Comment by janawueTUB** [comment]
I couldn't find out how findy handles DIDComm an "unwanted" DIDComm invitation. As far as I understood this scenario is indeed possible in their flow. Maybe it would be interesting to have a closer look on that in order to find a solution for our issue #6.

**Comment by janawueTUB** [comment]
The approach from findy does not match our solution: They use a DIDComm invitation based approach and 
use the creation of the DIDComm channel to replace the Login via username and password. This means in fact that the creation of the DIDComm channel in their solution is never optional.

**Comment by ArPhil** [comment]
Closed. They different things than we do.
